data-path = "/usr/app/data"

rpc-http-enabled = true
rpc-http-api = ["ETH", "NET", "WEB3", "QBFT"]
rpc-http-port = 8548

p2p-port = 30305

host-allowlist = ["*"]

rpc-http-cors-origins = ["*"]

genesis-file = "/usr/app/genesis.json"

min-gas-price = 0
